services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
